name: Deploy to Devcode Hosting on push develop
on:
  push:
    branches:
      - develop

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
