steps:
  - name: Upload coverage reports to Codecov
    uses: codecov/codecov-action@v3
    with:
      token: ${{ secrets.CODECOV_TOKEN }}
    comment: # this is a top-level key
      layout: "reach, diff, flags, files"
      behavior: default
      require_changes: false # if true: only post the comment if coverage changes
      require_base: no # [yes :: must have a base report to post]
      require_head: yes # [yes :: must have a head report to post]
